# SPDX-FileCopyrightText: 2025, FANUC America Corporation
# SPDX-FileCopyrightText: 2025, FANUC CORPORATION
#
# SPDX-License-Identifier: Apache-2.0

planning_plugin: pilz_industrial_motion_planner/CommandPlanner
request_adapters: ""
default_planner_config: PTP
capabilities: >-
  pilz_industrial_motion_planner/MoveGroupSequenceAction
  pilz_industrial_motion_planner/MoveGroupSequenceService
